default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  username: postgres
  password: mateo525

development:
  <<: *default
  database: savingsclub_development

# test:
#   <<: *default
#   database: savingsclub_test

# production:
#   <<: *default
#   database: savingsclub_production
#   username: savingsclub
#   password: <%= ENV['SAVINGSCLUB_DATABASE_PASSWORD'] %>
